[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vectorizer-svg"
version = "0.1.3"
description = "Simple linear algebra library"
authors = [{ name="0xSaad"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = ["vectorizersvg"]
